alias l="ls -GFlha"
alias q="clear"
alias grep="grep --color=always"
alias tree="tree -Cx --dirsfirst"
alias ./zshrc="vim ~/.zshrc"
alias ./vimrc="vim ~/.vimrc"
alias graph='git log --graph --abbrev-commit --decorate --format=format:'\''%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n'\'\''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)'\'' --all'
alias gst="git status"
alias grs="git restore --staged ."
alias add="git add ."
alias commit="git commit"
alias commitm="git commit -m"
alias clone="git clone"
alias react="npx create-react-app"
alias youtubeMp3="youtube-dl -x --audio-format mp3 --playlist-start 1 --playlist-end 50"
alias p="pwd"
alias repl="node-prototype-repl"
alias run="runC.sh"
alias python="python3"
alias tree="tree -CI 'node_modules'"

PATH=~/root/bin:/usr/local/Cellar/:$PATH
